### ISSUE TITLE
speakers chat

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/llvm-distributors-conf-2021#23]
cc @gburgessiv @serge-sans-paille @aleclearmind @berolinux @pirama-arumuga-nainar @zmodem @aaupov @hyp @petrhosek @skganesan @tstellar @smithp35 @mstorsjo @compnerd @Ericson2314 @carlocab @RoboTux

Hi speakers, thanks for taking the time to submit a CFP; we look forward to all of your talks.  Let's use this issue to discuss issues or questions for speakers.  You can also email me <ndesaulniers@google.com>, chat on the LLVM discord in #clang-built-linux, or #clangbuiltlinux on IRC on Libera.

I've published [a tentative schedule](https://github.com/ClangBuiltLinux/llvm-distributors-conf-2021#schedule), please take a look and let me know if you'd like to move your talk earlier or later.  We probably wont be able to accommodate all requests.

I'm hoping that speakers can join up to 1 hr before the doors open to test your setup; I think the room has a 200 person limit, and I can't save spaces.  I don't know if that will be a problem, but the speakers should join before the conference starts to ensure they're able to join.  I'll publish the room link soon.

Questions?

**Comment by fcremo** [comment]
Hi!
We would like to be moved to an earlier slot to better accommodate our timezone, if possible. Ideally, we would like to be placed before 10 PDT, if some other speaker is willing to swap their slot with ours.
We should be able to join the room earlier, thanks for the heads up!

**Comment by zmodem** [comment]
I also wouldn't mind an earlier slot due to my time zone if anyone is willing to swap. I'll still watch the whole thing, but may present better earlier during the night :)

**Comment by nickdesaulniers** [comment]
@compnerd may I switch you with @zmodem ?
@hyp may I switch you with @fcremo ?

**Comment by tstellar** [comment]
I don't mind moving later.

**Comment by mstorsjo** [comment]
I'd appreciate a slightly later timeslot if possible too - anytime between the first break (9.25) and the lunch break (12.40) should work best for me, worst case I can also take a slot after the lunch break.

**Comment by aaupov** [comment]
Hi @nickdesaulniers, @gburgessiv
I think it would make sense to swap the order of topics "PGO'ed toolchains" and "Clang with BOLT". In my talk, there's a data point of Clang performance with LTO+PGO and LTO+PGO+BOLT. So it would be natural to present BOLT after PGO. What do you think?

**Comment by nickdesaulniers** [comment]
Speakers, we're going to be using Google Meet to present. The link is in the Google Calendar invite I sent you.  Please don't share it yet; it's ok if you have though.

Please try joining (that link should already work) when convenient to test your setup.  You'll be in charge of sharing your slides; there's a button in the bottom to share your window or tab.  If you mute yourself and speak into your mic, you should get a popup asking if you meant to unmute; that's a good mic test.

I'm trying to setup a YouTube live stream.  I don't know if it will work, or be setup in time. There's a fair amount of internal red tape involved I'm trying to hack through.  They want me to share this disclaimer though for presenters joining the Google Meet:

> This event is being Livestreamed and Recorded. By entering this area, you consent to having your image and voice appear on  YouTube. 
> Thank you.

If you don't want to be recorded; I recommend closing out your CFP.  Otherwise I plan to post recordings to YouTube (whether we use YouTube for the live stream or not).  I have a bunch of paperwork to do for that today, and will know more tomorrow.

The goal is to have presenters in the Google Meet, and us advertising the link to the livestream on YouTube (which is why I'd prefer you don't share the Google Meet code, yet).

If I can't get the YouTube stream setup, we'll just have one big Google Meet and see how it goes.

Questions?

**Comment by nickdesaulniers** [comment]
I've sent an email about the release form for broadcasting+hosting recordings on YouTube. PTAL.

The (Public) YouTube Link for tomorrow will be: https://youtu.be/UMDRAmmDBgM. Please do share this. I will add it to the readme.  It is for attendees, but **NOT SPEAKERS**.

The ("Unlisted" ie. semi private) YouTube Link for rehersal tomorrow 1hr before doors open is [this](https://youtu.be/sku3Hx6vllU). Speakers do not need to attend; it's more so to verify the stream+encoders work.  Feel free to stop by though if you have last minute questions.

The (Private) Google Meet code is in the calendar invite. Please do not share that (yet).  Please do use that yourselves for dialing into Google Meet, where you will be presenting your slides, and sharing your own screen/tab to do so and control advancing through your slides at your pace.

In the event of an emergency with the Live Stream, we will simply be sharing the Google Meet code publicly.  The decision to do so will be last minute based on the rehersal; but everything seems to be working so far (we just tested the setup; up to the point of "going live," but the encoders were streaming from Meet to YouTube AFAICT).  Hopefully that stays a contingency.

**Comment by nickdesaulniers** [comment]
To keep a high throughput on content, we won't be doing questions live after the talk.  Please encourage folks to reach out via the relevant github issues filed for your CFPs; they're meant to be a place to follow up with people.  If we have time after all of the talks (ie. no SNAFUs where folks need to be rescheduled last minute say due to technical difficulties), then I figure we can all "hang out," and I'll try to pull live comments from the YouTube stream.  We'll have live comments plus live comment playback plus (traditional) comments enabled on the videos.  I'm discussing with the LLVM foundation moving the recording to their YouTube channel once available.

**Comment by nickdesaulniers** [comment]
@robotux and I verified the livestreaming is working :)

**Comment by nickdesaulniers** [comment]
Please don't use the chat in Google Meet; it will create a popup on the YouTube live stream; it's not private.

**Comment by hyp** [comment]
> 
> The (Private) Google Meet code is in the calendar invite. Please do not share that (yet). Please do use that yourselves for dialing into Google Meet, where you will be presenting your slides, and sharing your own screen/tab to do so and control advancing through your slides at your pace.
> 


@nickdesaulniers I don't think I have received the calendar invite with the google meet link, could you send it to aleksei_lorenz@apple.com.

**Comment by geofft** [comment]
The YouTube stream says "Chat is disabled for this stream." Is there a place where attendees (not speakers) can ask questions etc.? (If there's an IRC or Discord channel that people are on, that works too)

**Comment by nathanchance** [comment]
@geofft Yes, the CFP issue of the respective talk in this repo is the canonical place for questions.  We do have both IRC and Discord (linked on [our homepage](https://clangbuiltlinux.github.io)) that can be used to ask questions if the speaker is present there as well.

**Comment by nickdesaulniers** [comment]
ah, I thought I had enabled YouTube Live chat...hmm...maybe I made a mistake

**Comment by RoboTux** [comment]
On my Android app it says live chat does not work for child content.

**Comment by nickdesaulniers** [comment]
oops, I marked the stream as "Made for kids" which I guess doesn't mean "kid friendly" so live chat was disabled: https://support.google.com/youtube/answer/9527654?hl=en#what_happens.

**Comment by nickdesaulniers** [comment]
ok, I think was able to fix that. Folks may need to refresh their stream.
https://support.google.com/youtube/answer/9527654?hl=en#what_happens

**Comment by stephenhines** [comment]
😂 Thinking about the juxtaposition of people talking about "build systems" and "Made for kids / kid friendly".

**Comment by nickdesaulniers** [comment]
@Ericson2314 can you pick back up during the break?

**Comment by nickdesaulniers** [comment]
Thanks everyone for giving great talks today! Like I said; I hope
we can address some of the enumerated difficulties so that we might
laugh about the bad old days soon together.

Please send a PR adding your slides, or just email them to me. I will
pester the hell out of you until I get them. ❤️ ie. @petrhosek @compnerd @hyp @Ericson2314 @zmodem @serge-sans-paille @sylvestre @gburgessiv @tstellar
